18F/brand

- Gemfile
- Gemfile.lock
- _config.yml
- _includes/scripts.html
- _plugins/uswds.rb
- _sass/uswds
- css/main.scss
The symlink wasn't working due to the issues discussed in:
https://github.com/guard/listen/wiki/Duplicate-directory-errors
The solution was to write a very tiny plugin to add the web-design-standards
submodule to the Sass load paths, then explictly exclude all items from
web-design-standards that shouldn't appear in the output.
cc: @maya
> Add Gemfile, enable US Web Design Std integration

- _includes/sidenav.html
This adds `{{ site.baseurl }}` to sidenav parent links so they work. cc @jenniferthibault
> Add baseurl to sidenav parent links

- .gitignore
- Gemfile
- Gemfile.lock
This upgrades the project from Jekyll 2.5.3 to 3.1.6.
The main benefit I was hoping to take advantage of was Jekyll 3's [incremental regeneration](http://idratherbewriting.com/2015/11/04/jekyll-30-released-incremental-regeneration-rocks/). Currently making a simple change to the site's SASS takes a couple seconds on my machine, which makes rapidly tinkering with styling a bit more cumbersome, and I was hoping that running jekyll with `--incremental` would speed it up, but it doesn't. :disappointed: 
In any case, though, there are probably other benefits to using Jekyll 3 that I don't know about, and it's probably a good idea to upgrade sooner anyways since support for 2.x will be dropped at some point. I browsed the built website with this new version and there don't seem to be any …
> Upgrade to Jekyll 3

- _sass/_styleguide.scss
When the page content isn't enough to fill the whole viewport, the footer isn't actually at the bottom of the page:
~~This PR isn't an ideal fix, but it basically ensures that the content element is at least the full height of the viewport, so that the footer is always at the very bottom of the page. However, the downside of this fix is that in such cases, the footer actually needs to be scrolled-down to. So it's OK if you end up rejecting this PR. (The traditional sticky footer fix requires a fixed-height footer, which I don't like, and the [flexbox version](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) was exhibiting some weird graphical anomalies. So that's why I didn't go either of those routes.)~~
This PR uses a [flexbox-based sticky …
> Make footer sticky.

- Gemfile
- Gemfile.lock
- _data/palette.yml
- _includes/color-matrix.html
- _plugins/contrast_ratio.rb
- _sass/_color-matrix.scss
- css/main.scss
- visual-style.html
This is an attempt to make the color matrix accessible, and also generally easier to modify if needed, by converting it to HTML. It fixes #51.
For the duration of this PR, you can view the proposed changes live at https://brand-html-color-matrix.apps.cloud.gov/visual-style/#colors.
Here's a screenshot of the HTML color matrix on **Large** screens (≥1201px, as defined by USWDS):
I also defined a new breakpoint called **Marge** (≥992px), which is like a cross between USWDS's Medium (≥600px) and Large. It's based off Bootstrap's "Medium" size.
On Marge screens, the table cell padding is condensed, the fonts are a bit smaller, and the first column is laid out vertically:
Finally, anything smaller than Marge gets the mobile treatment, which is a compromise between @rtwell's awesome mockups in …
> Make color matrix accessible

- README.md
- _includes/color-matrix.html
- _sass/_styleguide.scss
- pages/color-palette.html
- pages/desktop-art.html
- pages/introduction.html
- pages/logo.html
- pages/presentation-themes.html
- pages/typography.html
- Repositions the copy throughout the site to acknowledge readers from outside of 18F in preparation for moving off staging https://github.com/18F/brand/issues/83
- Brings content in line with the 18F Content Guide recommendations
- Moves Instructions and Guidelines for use out of PDFs and directly on the page. 
- Resolves https://github.com/18F/brand/issues/85
- Removes one desktop art image that we couldn't find the citation for
- Incorporates licensing info on custom fonts h/t @thisisdano 
- Small changes to link styling, including:
- Removing the visual difference between visited and not-yet-visited links
- Making links in lists the same style as links out of lists. Previously links inside lists did not have underlines
@nicoleslaw to review my implementation of her formatting
These …
> Preparing the site for public viewing

- .gitignore
- _sass/_styleguide.scss
- pages/typography.html
Added type specimens to the typography page and tweaked the styles to make it all look right. Pretty much copied the USWDS page here: https://standards.usa.gov/typography/
- - -
> Type specimens for typography page

- _includes/sidenav.html
- pages/color-palette.html
- pages/desktop-art.html
- pages/templates.html
This begins completion criteria for https://github.com/18F/visual-design/issues/27#issuecomment-293404713
- Changes "Presentation themes" page to "Templates" page to be more inclusive 
- Adds front content for Google Doc template
- Makes font hierarchy consistent across other sections, especially applied to "Instructions" as an `h3` instead of an `h2`
(Ignore the duplicated side nav which is an artifact of my screen shot tool)
cc @amberwreed and @austinhernandez for visibility
> Creates template section

- pages/logo.html
Link has a 404 error.
New link correctly goes to template page which has light-blue 18F logo
> Fix broken link

- pages/color-palette.html
- pages/templates.html
- pages/typography.html
- Removes support for the Keynote template and and references to it. Resolves #145 
- Updates installation instructions to include both making a presentation from scratch, and re-theming an existing presentation.
- Directs users to the GSA template gallery to select a new document instead of bringing them directly into the master template. This should help people avoid accidentally editing the master template AND reduce the number of files we need to maintain to avoid this scenario.
And a few smaller things:
- Adds a missing alt tag for the cover slide
- Removes references to keynote from other pages
😎 [PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/brand/template-links/templates/)
> Update slide template links

- _includes/sidenav.html
- pages/principles.html
Adds visual design principles for 18F to the visual identity guide site.
😎 [PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/brand/principles/principles/)
[A long long time ago](https://github.com/18F/visual-design/issues/32) @amberwreed & @thisisdano facilitated the team to develop visual design principles that applied to 18F's visual identity work. 
We meant to add them to this site, but after folks left 18F or moved to other parts of the org, they got parked in the wiki instead: https://github.com/18F/brand/wiki/18F-Brand-visual-design-principles-(draft). With @alexsoble 's help I finally got past the Ruby errors that were preventing me from running the site locally, and now HERE THEY ARE!
As a follow up to this PR, we should remove them from the wiki so that information …
> Add principles to site

- pages/icons.html
This is so neat, but I thought at first the google slide template might be public. Adding this clarifies its not.
> add a note that this only applies to GSA staff

- pages/icons.html
I wanted to suggest adding some language and links to the avatar work you've done to the Icons pages. Feel free to reject if you have decided this shouldn't be part of the brand site. It occurred to me because I was looking for the avatar stuff on the website, couldn't find it, and then it took me a while to find it in Slack. 
[Preview link](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/brand/18F-Avataaars/icons/)
> Adding link to 18F Avataaar resources

- _includes/footer.html
The git links in the footer go to an old repo url
- updating contributing link
- updating license link
> fixing git links in footer

- _sass/_uswds-theme-custom-styles.scss
- pages/typography.md
Sets up the typography page, closes #236 . In order to display the two weights side by side I'm using html within the markdown file for the bottom half.
> Convert typography page to new md format

- _sass/_uswds-theme-custom-styles.scss
Fixes a few small styling bugs I noticed at our demo yesterday, including:
* Fixing the button text color on the logo page
* Fixing the mobile active nav item indicator bar
@igorkorenfeld passing to you for your review! Before and after's below. 
[Federalist preview link](https://federalist-9413b3a7-6641-4d7e-bf2d-fd9440417d07.app.cloud.gov/preview/18f/brand/ik-setup-theme--buttonfix/)
----
Before
After
Before
After
> fixing button text color, fixing active nav item indicator on mobile

- Gemfile.lock
- _config.yml
- javascript/external-links.js
This PR adds external link icons to most links, adding in exceptions for google doc, google drive, and slack (which get the private eye lock icon)
👓  [preview](https://federalist-9413b3a7-6641-4d7e-bf2d-fd9440417d07.app.cloud.gov/preview/18f/brand/link-icons/)
> Add external link icons with exceptions

- _data/usa_anchor.yaml
- _includes/footer.html
This PR adds a contact us link to the footer and a privacy policy link to the identifier in order to meet the digital council requirements 
👓 [Preview](https://federalist-9413b3a7-6641-4d7e-bf2d-fd9440417d07.app.cloud.gov/preview/18f/brand/ik_add-req-links/)
> Add contact and privacy links

- _includes/color-matrix.html
This PR updates the file generating the color contrast matrix so that screen readers don't read "image" for the grey "don't use" color blocks. This makes it consistent with the good color combinations, where the screen reader only reads the combination of colors and announces the color contrast. 
This should also address the failing compliance tests
👓 [Federalist preview](https://federalist-9413b3a7-6641-4d7e-bf2d-fd9440417d07.app.cloud.gov/preview/18f/brand/ik/contrast-alt-text/color-palette//)
> Fix SR reading "image" on color contrast matrix

- pages/introduction.md
Fixes #284
This PR updates a link on the introduction page that lists the core values, but the link is broken. This points it to the right page that just got moved.
> Update broken "Our Core Values" link
